### ISSUE TITLE
Conexión a base de datos

### ISSUE THREAD

**Issue by esthervity1987** [esthervity1987/LibreriaPepito#3]
Añade la conexión a la base de datos dentro del proyecto en la carpeta conexión.

**Comment by miguelamd0** [comment]
Los archivos subidos son dos:

- librosDB.sql dónde se crea la base de datos, la tabla y se insertan datos. También se crea el usuario que utilizará la aplicación para obtener datos de la DB.

- Modelo.php. Contiene la clase PatronSingleton que conecta con PDO con la base de datos. También contiene el método de búsqueda de libros que devuelve un array de arrays asociativos de libros.
